### ISSUE TITLE
Indicates that the.npz file cannot be found

### ISSUE THREAD

**Issue by 1301358882** [jianjieluo/SCD-Net#8]
Hello, when I was training 1_train_xe.sh, there was no error 446093.npz, how can I solve this problem? Previous address path... /open_source_dataset/mscoco_dataset/features/up_down The data can be queried.
![微信图片_20231129154842](https://github.com/jianjieluo/SCD-Net/assets/139096668/98314cd8-74e2-45a6-b696-fef3deff5dd0)

**Comment by lph223** [comment]
May I ask if your problem has been resolved？

**Comment by 1301358882** [comment]
> May I ask if your problem has been resolved？

just do the python tools/create_feats.py operation for each.tsv

**Comment by lph223** [comment]
运行create_feats.py文件报错，请问这个问题怎么解决
tools/create_feats.py:27: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
  item[field] = np.frombuffer(base64.decodestring(bytes(item[field], 'utf-8')),
Traceback (most recent call last):
  File "tools/create_feats.py", line 41, in <module>
    main(args)
  File "tools/create_feats.py", line 32, in main
    np.savez_compressed(os.path.join(args.outfolder, str(image_id)), feat=feats)
  File "<__array_function__ internals>", line 5, in savez_compressed
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 689, in savez_compressed
    _savez(file, args, kwds, True)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 715, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
  File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/root/miniconda3/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'open_source_dataset/mscoco_dataset/feature/up_down_10_100/524881.npz

**Comment by 1301358882** [comment]
> 运行create_feats.py文件报错，请问这个问题怎么解决 tools/create_feats.py:27: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes() item[field] = np.frombuffer(base64.decodestring(bytes(item[field], 'utf-8')), Traceback (most recent call last): File "tools/create_feats.py", line 41, in main(args) File "tools/create_feats.py", line 32, in main np.savez_compressed(os.path.join(args.outfolder, str(image_id)), feat=feats) File "<**array_function** internals>", line 5, in savez_compressed File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 689, in savez_compressed _savez(file, args, kwds, True) File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 715, in _savez zipf = zipfile_factory(file, mode="w", compression=compression) File "/root/miniconda3/lib/python3.8/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory return zipfile.ZipFile(file, *args, **kwargs) File "/root/miniconda3/lib/python3.8/zipfile.py", line 1251, in **init** self.fp = io.open(file, filemode) FileNotFoundError: [Errno 2] No such file or directory: 'open_source_dataset/mscoco_dataset/feature/up_down_10_100/524881.npz

item[field] = np.frombuffer(base64.decodebytes(bytes(item[field],encoding="utf8"))
I did make some changes here.

**Comment by lph223** [comment]
Do other areas still need to be modified

**Comment by 1301358882** [comment]
> Do other areas still need to be modified

The data address needs to be changed, you can look at the code

**Comment by lph223** [comment]
Traceback (most recent call last):
  File "tools/create_feats.py", line 39, in <module>
    main(args)
  File "tools/create_feats.py", line 15, in main
    for item in reader:
  File "/root/miniconda3/lib/python3.8/csv.py", line 111, in __next__
    row = next(self.reader)
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)

def main(args):      
    count = 0
    with open(args.infeats, "r+b") as tsv_in_file:
        reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames = FIELDNAMES)
        for item in reader:
            if count % 1000 == 0:
                print(count)
            count += 1

            item['image_id'] = int(item['image_id'])
            item['image_h'] = int(item['image_h'])
            item['image_w'] = int(item['image_w'])
            item['num_boxes'] = int(item['num_boxes'])
            for field in ['boxes', 'features']:
                item[field] = np.frombuffer(base64.decodebytes(bytes(item[field], 'utf-8')),
                        dtype=np.float32).reshape((item['num_boxes'],-1))
            image_id = item['image_id']                    
            
            feats = item['features']
            np.savez_compressed(os.path.join(args.outfolder, str(image_id)), feat=feats)
            
if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('--infeats', default='trainval/karpathy_train_resnet101_faster_rcnn_genome.tsv.0', help='image features')
    parser.add_argument('--outfolder', default='open_source_dataset/mscoco_dataset/feature/up_down', help='output folder')

    args = parser.parse_args()
    main(args)
